name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Start development server
        run: npm build & npm start

      - name: Wait for the server to start
        run: sleep 30

      - name: Run Cypress tests
        run: npx cypress run --config baseUrl=http://localhost:3000
